version: '2'
services:
    nginx:
        container_name: nginx
        restart: always
        image: nginx:alpine
        ports:
            - 80:80
        depends_on:
            - php
        volumes: 
            - ./SSPanel-Uim:/usr/www/html
            - ./file/nginx:/etc/nginx/conf.d
        environment: 
            - TZ=Asia/Shanghai

    php:
        container_name: php
        restart: always
        image: gtary/php:ssp
        depends_on:
            - mariadb
        volumes: 
            - ./SSPanel-Uim:/var/www/html
        environment: 
            - TZ=Asia/Shanghai

    mariadb:
        container_name: mariadb
        restart: always
        image: mariadb
        environment: 
            - TZ=Asia/Shanghai
            - MARIADB_ROOT_PASSWORD=599f6f06-3eae-404c-bd69-16d9a62d6458
        volumes: 
            - /var/lib/mysql:/var/lib/mysql
            - ./SSPanel-Uim/sql:/tmp/sql
            - ./file/mariadb:/etc/mysql/conf.d

    phpmyadmin:
        container_name: phpmyadmin
        restart: always
        image: phpmyadmin
        depends_on:
            - mariadb
        ports:
            - 888:80
        environment: 
            - PMA_ARBITRARY=1
            - TZ=Asia/Shanghai