services:
    nginx:
        container_name: nginx-2025
        restart: always
        image: nginx:alpine
        ports:
            - 8080:80
        depends_on:
            - php
        volumes:
            - ./file/nginx:/etc/nginx/conf.d
            - ./SSPanel-Uim:/usr/www/html
        environment:
            - TZ=Asia/Shanghai

    php:
        container_name: php-2025
        restart: always
        image: gtary/ssp:php
        depends_on:
            - mariadb
            - redis
        volumes:
            - ./SSPanel-Uim:/var/www/html
        environment:
            - TZ=Asia/Shanghai

    mariadb:
        container_name: mariadb-2025
        restart: always
        image: mariadb:lts
        environment:
            - TZ=Asia/Shanghai
            - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
        volumes:
            - /opt/data/mysql:/var/lib/mysql
            - ./SSPanel-Uim/db:/tmp/sql
            - ./file/mariadb:/etc/mysql/conf.d

    redis:
        container_name: redis-2025
        restart: always
        image: redis
        ports:
            - 6379:6379
        volumes:
            - /opt/data/redis:/data
        environment:
            - TZ=Asia/Shanghai

    phpmyadmin:
        container_name: phpmyadmin-2025
        restart: always
        image: phpmyadmin
        depends_on:
            - mariadb
        ports:
            - 888:80
        environment:
            - PMA_ARBITRARY=1
            - TZ=Asia/Shanghai