version: '2'
services:
    nginx:
        container_name: nginx
        restart: always
        image: gtary/ssp:nginx
        ports:
            - 80:80
        depends_on:
            - php
        volumes:
            - ./SSPanel-Uim:/usr/www/html
        environment:
            - TZ=Asia/Shanghai

    php:
        container_name: php
        restart: always
        image: gtary/ssp:php
        depends_on:
            - mariadb
        volumes:
            - ./SSPanel-Uim:/var/www/html
        environment:
            - TZ=Asia/Shanghai

    mariadb:
        container_name: mariadb
        restart: always
        image: mariadb:lts
        environment:
            - TZ=Asia/Shanghai
            - MARIADB_ROOT_PASSWORD=sspanel
        volumes:
            - /var/lib/mysql:/var/lib/mysql
            - ./SSPanel-Uim/db:/tmp/sql
            - ./file/mariadb:/etc/mysql/conf.d

    phpmyadmin:
        container_name: phpmyadmin
        restart: always
        image: phpmyadmin
        depends_on:
            - mariadb
        ports:
            - 888:80
        environment:
            - PMA_ARBITRARY=1
            - TZ=Asia/Shanghai